openapi: 3.0.3

info:
  title: Kitchen API
  description: API that allows to manage the production of orders in the kitchen
  version: 1.0.0

servers:
  - url: http://127.0.0.1:5000
    description: URL for local development and testing
  - url: https://coffeemesh.com
    description: main production server
  - url: https://coffeemesh-staging.com
    description: staging server for testing purposes only

paths:
  /kitchen/schedules:
    get:
      summary: Returns a list of orders sheduled for production
    post:
      summary: Schedules an order for production

  /kitchen/schedules/{schedule_id}:
    get:
      summary: Returns the status and details of a scheduled order
    put:
      summary: Updates an existing scheduled order

  /kitchen/schedules/{schedule_id}/status:
    parameters:
      - in: path
        name: schedule_id
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Returns the status of a scheduled order

  /kitchen/schedules/{schedule_id}/cancel:
    parameters:
      - in: path
        name: schedule_id
        required: true
        schema:
          type: string
          format: uuid
    post:
      summary: Cancels a scheduled order

components:
  responses:
    NotFound:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string

    OrderItemSchema:
      additionalProperties: false
      type: object
      required:
        - product
        - quantity
        - size
      properties:
        product:
          type: string
        size:
          type: string
          enum:
            - small
            - medium
            - big
        quantity:
          type: integer
          minimum: 1

    ScheduleOrderSchema:
      type: object
      additionalProperties: false
      required:
        - order
      properties:
        order:
          type: array
          items:
            $ref: "#/components/schemas/OrderItemSchema"

    GetScheduledOrderSchema:
      type: object
      additionalProperties: false
      required:
        - id
        - order
        - scheduled
        - status
      properties:
        id:
          type: string
          format: uuid
        scheduled:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - pending
            - progress
            - cancelled
            - finished
        order:
          type: array
          items:
            $ref: "#/components/schemas/OrderItemSchema"

    ScheduleStatusSchema:
      type: object
      additionalProperties: false
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - pending
            - progress
            - cancelled
            - finished
